// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://edxjoptogxgmsbwdwvxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkeGpvcHRvZ3hnbXNid2R3dnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzIzMTAsImV4cCI6MjA3MDAwODMxMH0.LwT6Hd9D3Rh2qIS15QKKTv5FLX4Wgqjn9xn-la3N8go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
